
import java.awt.image.BufferedImage;
import java.io.BufferedInputStream;
import java.io.File;
import java.io.IOException;
import java.util.*;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.util.Random;

import javax.swing.JFrame;
import javax.swing.JPanel;


public class HeatTranslate {

	public HeatTranslate()
	{ }

	
	public void openingMessage()
	{
		System.out.println("Welcome to the Heat Map Translation Software for the Eye Tribe client. \n"
				+ "this software reads a text file generated by the eyetribes UI, parses the data, \n and displays the heat map of "
				+ "the users eye cooridinates in real time. ");
		
		System.out.println("Enter directory to the Eye Tribe Text file to be translated...");
		
	}
	
public String parseCoords(File file) throws IOException{
	  
		Scanner input = new Scanner(file);
		String temp = "";
	    String x = "";
	    String y = "";
	    String coords = "";
	    
	    //TODO
	    int indexOfBackwardsBrace, indexOfComma;
		int lineCount = 0;
		
		while(input.hasNext()){
	        
	    	String[] tokens =  input.nextLine().split("\\{");
	    	
	    	if(tokens.length > 1){ 
	    		try {
	    		
	    			temp = tokens[4]; 	
	    			indexOfBackwardsBrace = temp.indexOf('}');
	    			
	    			temp = temp.substring(0, indexOfBackwardsBrace);
	    			indexOfComma = temp.indexOf(',');
	    			
	    			x = temp.substring(4, indexOfComma);
	    		    y = temp.substring(indexOfComma + 5, temp.length());
	    		
	    		    coords += x + "," + y + "-";
	    		    
	    		} catch (Exception e) {
					
	    			System.out.println("HeartBeat, Skipped Line");
	    		}		
	    	}
	    	lineCount++;
		}
		return coords;
	}
	
	public static void main(String[] args) throws IOException {
		
		String xCoord = "";
	    String yCoord = "";
		double x, y;
	    
		File test  = new File("/Users/Quiksilvr/Documents/workspace/HeatMap/src/min.txt"); 
		
		HeatTranslate HT = new HeatTranslate();
	    Display display = new Display();
			
	    String [] nextString = HT.parseCoords(test).split("-");
		
	    for(int i = 0; i < nextString.length; i++)
		{
			xCoord = nextString[i].substring(0, nextString[i].indexOf(','));
			yCoord = nextString[i].substring(nextString[i].indexOf(',') + 1, nextString[i].length());
		    
			x = Double.parseDouble(xCoord);
			y = Double.parseDouble(yCoord);
			
			display.setCoordinates(x , y);
			display.repaint();
			
			try {
				Thread.sleep(100);
			} catch (InterruptedException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
			
		}
 	}
}
	

